fix PriceOracleAdapterMoC to return usdc value
riflending/rlending-protocol pull request #23
Opened 2020-12-07 17:02 UTC by fgregoribattista

fix price oracle adapter MoC

2020-12-07 19:34 UTC, pmprete requested changes

2020-12-07 19:34 UTC, pmprete commented on tests/PriceOracleProxyTest.js
> +      await readAndVerifyOraclePrice(cRIF, tokenPrice / new BigNumber('1e18'), priceAdapterMoc);
creo que no deberia ir dividido nada aca

2020-12-07 19:38 UTC, fgregoribattista commented on tests/PriceOracleProxyTest.js
> +      await readAndVerifyOraclePrice(cRIF, tokenPrice / new BigNumber('1e18'), priceAdapterMoc);
se divide, ya que la funcion readAndVerifyOraclePrice internamente lo esta multiplicando por 1e18 para obtener el valor deseado.

2020-12-07 19:41 UTC, pmprete commented on tests/PriceOracleProxyTest.js
> +      await readAndVerifyOraclePrice(cRIF, tokenPrice / new BigNumber('1e18'), priceAdapterMoc);
tenes razon

2020-12-08 14:20 UTC, pmprete approved these changes
Great Work Facu

2020-12-08 14:21 UTC, merged